### ISSUE TITLE
Provide a way to set radius and time period

### ISSUE THREAD

**Issue by gilles-morain** [kevinlacaille/planet_hack_2020_deforestation#11]
Best way would probably be a radius param in the redirect route

**Comment by guy1ziv2** [comment]
I also suggest moving to days and not weeks and having before_days and after_days in params in redirect URL, with all three having default settings  in params fuke

**Comment by gilles-morain** [comment]
Added rm (radius in meters), db (days before) and da (days after) optional parameters

Example: /api/v1/notice?id=202&rm=7000&db=5&da=10
