### ISSUE TITLE
Provide a way to give Planet API key

### ISSUE THREAD

**Issue by guy1ziv2** [kevinlacaille/planet_hack_2020_deforestation#14]
Currently uses PL_API_KEY environmental variable, make it accept API key as parameter in redirect. It is probably better not to stored ANY API keys with the App

**Comment by gilles-morain** [comment]
Not sure the alternative is better: would you let an API key in a Google Sheet document ? We can however have an overload option so if you want the app to search with your own key when manually interrogating the API that's doable for sure. I still think the app needs a default API key hidden from the Google Sheet users

**Comment by guy1ziv2** [comment]
Yes, I see your point.

**Comment by gilles-morain** [comment]
Added a `/setenv?PL_API_KEY=<...>` route that can be enabled using the `SETENV_ENABLED` config parameter, but this effectively replaces the key used globally by the app in commit cdc4432dbaf9eef21ba2aafb1f3bce6ed19ecf7f
