### ISSUE TITLE
Limit area cover

### ISSUE THREAD

**Issue by guy1ziv2** [kevinlacaille/planet_hack_2020_deforestation#19]
If possible, set a (configurable) threshold on % of area covered by Planet images within polygon?

**Comment by guy1ziv2** [comment]
There is nothing in meta-data to search for, but this is probably not so difficult as a post API call. The Data API returns polygons so we can intersect those with our AOI and filter the IDs based on that?

**Comment by guy1ziv2** [comment]
I tried to implement this on line 193+ but it still give Planet images w/ small overlap, not sure why....

**Comment by guy1ziv2** [comment]
@gilles-morain maybe you have some ideas?

**Comment by gilles-morain** [comment]
@guy1ziv2 the idea would be to filter out images not providing enough coverage inside the polygon, right ?

**Comment by guy1ziv2** [comment]
Yes. I think, however, that the URLs we generate dont actually filter to the set of image_ids as we think.

**Comment by gilles-morain** [comment]
Actually, it is the Explorer web UI that does the additional filtering when you use the 'Area Coverage' filter. Hitting Apply filters does not send a new search request (as the browser debug tools show) => all images returned by the possible API search criteria (which do not include % of AOI coverage) are returned into the left pane, so we do not have control of this (unless building a new web app). What works though is the left/right selection based on the % of AOI coverage. If you try e.g. http://127.0.0.1:5001/api/v1/notice?id=3&db=4&da=6 you will see that even though the left pane returns additional images, the outer bounds used for initial comparison map only use the min/max images matching the minimal intersection threshold. I suggest we close this issue if you don't mind

**Comment by guy1ziv2** [comment]
I guess so...

Guy Ziv
