### ISSUE TITLE
Find municipality boundaries in Brazil

### ISSUE THREAD

**Issue by gilles-morain** [kevinlacaille/planet_hack_2020_deforestation#3]

**Comment by skyprince999** [comment]
https://datacatalog.worldbank.org/dataset/2010-brazil-municipalities-location

Added the shape files to the repo `br_localidades_2010.zip`

**Comment by ultraasi-atanas** [comment]
The Worldbank Municipality data looks like this 
Granularity: 
City or metropolitan
![image](https://user-images.githubusercontent.com/55555430/96190798-b68ac680-0f3a-11eb-916e-27b7ecb3a9c4.png)
I had opened the br_localidades_2010/BR_Localidades_2010.shp in GQIS and it's the cities and towns - not borders?

**Comment by gilles-morain** [comment]
looking here https://en.wikipedia.org/wiki/Municipalities_of_Brazil it seems that Brazil has states as level 1 and municipalities as level 2 PLUS the the federal district. But for this project I think we can ignore this spatial oddity ;-)

That gives us a good candidate for municipality polygons : https://data.humdata.org/dataset/brazil-administrative-level-0-boundaries

**Comment by gilles-morain** [comment]
5572 features in the admin level 2 shapefile (QGIS fails to detect CRS, but it is actually EPSG:4326) ![image](https://user-images.githubusercontent.com/67698956/96196636-29eb0300-0f50-11eb-9af6-2b9bf24430d0.png)

**Comment by ultraasi-atanas** [comment]
That's much better, @BGCastro89 fyi

**Comment by skyprince999** [comment]
Wow! Looks beautiful!
