### ISSUE TITLE
How does access the wiki page?

### ISSUE THREAD

**Issue by skyprince999** [kevinlacaille/planet_hack_2020_deforestation#5]
Hi Kevin- I would like to edit the wiki (to-do) activities. Could you give the required permission. Or should I type it here? 

My to-do is to create a chart which will visualize all the areas of interest (as given in the ground-truth)

**Comment by kevinlacaille** [comment]
My mistake, I forgot to add you as a contributor! I'll do so now and you'll get an email, which you'll need to accept. Then you may post a wiki.
